-- GENERATED by database/scripts/export_scraper_schema.py from the pgs_db models.
-- Do not edit: change the models (and add an Alembic migration), then re-run the script
-- and `make sqlc` in scraper/.
--
-- The tables the Go scraper reads and writes, as sqlc needs them to generate the Go
-- models in scraper/internal/db (see scraper/sqlc.yaml). This is NOT a migration and
-- is never executed: the schema is created by the Alembic migrations in database/, and
-- the scraper connects as pgs_scraper, which cannot change it. Foreign keys to tables
-- outside this file are left out (sqlc would not know them); triggers and indexes are
-- not needed by sqlc.

CREATE TABLE crawl_runs (
	category VARCHAR(64),
	status VARCHAR(32) NOT NULL,
	temporal_workflow_id VARCHAR(255),
	started_at TIMESTAMP WITH TIME ZONE NOT NULL,
	finished_at TIMESTAMP WITH TIME ZONE,
	seed_count INTEGER,
	max_depth INTEGER,
	max_pages INTEGER,
	fetched_count INTEGER NOT NULL,
	succeeded_count INTEGER NOT NULL,
	failed_count INTEGER NOT NULL,
	skipped_count INTEGER NOT NULL,
	unique_url_count INTEGER NOT NULL,
	domain_capped_count INTEGER DEFAULT '0' NOT NULL,
	error TEXT,
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_crawl_runs PRIMARY KEY (id),
	CONSTRAINT ck_crawl_runs_crawl_run_status CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE TABLE domains (
	domain VARCHAR(255) NOT NULL,
	website_name VARCHAR(255),
	category VARCHAR(32) NOT NULL,
	status VARCHAR(32) NOT NULL,
	priority VARCHAR(32) NOT NULL,
	rate_limit_per_sec INTEGER NOT NULL,
	local_body_id BIGINT,
	last_crawled_at TIMESTAMP WITH TIME ZONE,
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_domains PRIMARY KEY (id),
	CONSTRAINT ck_domains_rate_limit_positive CHECK (rate_limit_per_sec > 0),
	CONSTRAINT uq_domains_domain UNIQUE (domain),
	CONSTRAINT ck_domains_domain_category CHECK (category IN ('GOVERNMENT', 'NEWS', 'EDUCATION', 'FINANCE', 'NGO', 'COMMERCIAL', 'OTHER')),
	CONSTRAINT ck_domains_domain_status CHECK (status IN ('PENDING', 'CRAWLING', 'PAUSED', 'COMPLETED', 'FAILED')),
	CONSTRAINT ck_domains_domain_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH'))
);

CREATE TABLE crawled_documents (
	crawl_run_id BIGINT,
	domain_id BIGINT,
	url TEXT NOT NULL,
	normalized_url TEXT NOT NULL,
	final_url TEXT,
	canonical_url TEXT,
	host VARCHAR(255),
	category VARCHAR(64),
	title TEXT,
	meta_description TEXT,
	meta_keywords TEXT[],
	open_graph JSONB,
	text TEXT,
	headings JSONB,
	json_ld TEXT[],
	emails TEXT[],
	phones TEXT[],
	address TEXT,
	social_links TEXT[],
	links TEXT[],
	anchor_texts TEXT[],
	internal_links TEXT[],
	external_links TEXT[],
	image_links TEXT[],
	video_links TEXT[],
	geo_lat FLOAT,
	geo_lng FLOAT,
	country VARCHAR(2),
	sim_hash BIGINT,
	depth INTEGER NOT NULL,
	status_code INTEGER,
	content_type VARCHAR(255),
	content_hash VARCHAR(64) NOT NULL,
	fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
	fetch_duration_ms BIGINT,
	error TEXT,
	minio_path TEXT,
	processing_status VARCHAR(32) DEFAULT 'UNPROCESSED' NOT NULL,
	processing_error TEXT,
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_crawled_documents PRIMARY KEY (id),
	CONSTRAINT uq_crawled_documents_normalized_url_content_hash UNIQUE (normalized_url, content_hash),
	CONSTRAINT fk_crawled_documents_crawl_run_id_crawl_runs FOREIGN KEY(crawl_run_id) REFERENCES crawl_runs (id),
	CONSTRAINT fk_crawled_documents_domain_id_domains FOREIGN KEY(domain_id) REFERENCES domains (id),
	CONSTRAINT ck_crawled_documents_processing_status CHECK (processing_status IN ('UNPROCESSED', 'PROCESSING', 'PROCESSED', 'FAILED', 'QUARANTINED'))
);

CREATE TABLE stored_files (
	crawled_document_id BIGINT,
	source_page_url TEXT NOT NULL,
	document_url TEXT NOT NULL,
	storage_path TEXT NOT NULL,
	content_type VARCHAR(255),
	sha256 VARCHAR(64) NOT NULL,
	size_bytes BIGINT NOT NULL,
	stored_at TIMESTAMP WITH TIME ZONE NOT NULL,
	processing_status VARCHAR(32) DEFAULT 'UNPROCESSED' NOT NULL,
	processing_error TEXT,
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_stored_files PRIMARY KEY (id),
	CONSTRAINT uq_stored_files_document_url_sha256 UNIQUE (document_url, sha256),
	CONSTRAINT fk_stored_files_crawled_document_id_crawled_documents FOREIGN KEY(crawled_document_id) REFERENCES crawled_documents (id),
	CONSTRAINT ck_stored_files_processing_status CHECK (processing_status IN ('UNPROCESSED', 'PROCESSING', 'PROCESSED', 'FAILED', 'QUARANTINED'))
);
