"""Write sql/scraper_schema.sql: the DDL of the tables the Go scraper uses, generated
from the pgs_db models (the source of truth, with the Alembic migrations).

The Go scraper has no schema of its own and never migrates anything: sqlc reads this
file (scraper/sqlc.yaml) only to generate the Go models and query code in
scraper/internal/db. Nothing ever executes it.

    python scripts/export_scraper_schema.py          # rewrite the file
    python scripts/export_scraper_schema.py --check  # exit 1 if it is out of date

Run it after a migration that changes one of these tables, then `make sqlc` in
scraper/. tests/test_scraper_schema_sync.py fails while the file is stale or the
models disagree with the migrated database.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from sqlalchemy import Table
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable

import pgs_db.models  # noqa: F401  (registers every table on Base.metadata)
from pgs_db.base import Base

# In dependency order (a foreign key only points at a table above it).
SCRAPER_TABLES = ("crawl_runs", "domains", "crawled_documents", "stored_files")
OUTPUT = Path(__file__).resolve().parents[1] / "sql" / "scraper_schema.sql"

HEADER = """\
-- GENERATED by database/scripts/export_scraper_schema.py from the pgs_db models.
-- Do not edit: change the models (and add an Alembic migration), then re-run the script
-- and `make sqlc` in scraper/.
--
-- The tables the Go scraper reads and writes, as sqlc needs them to generate the Go
-- models in scraper/internal/db (see scraper/sqlc.yaml). This is NOT a migration and
-- is never executed: the schema is created by the Alembic migrations in database/, and
-- the scraper connects as pgs_scraper, which cannot change it. Foreign keys to tables
-- outside this file are left out (sqlc would not know them); triggers and indexes are
-- not needed by sqlc.
"""


def _create_table(table: Table) -> str:
    keep = [fk for fk in table.foreign_key_constraints if fk.referred_table.name in SCRAPER_TABLES]
    ddl = CreateTable(table, include_foreign_key_constraints=keep)
    sql = str(ddl.compile(dialect=postgresql.dialect())).strip()
    return "\n".join(line.rstrip() for line in sql.splitlines()) + ";\n"


def render() -> str:
    tables = [Base.metadata.tables[name] for name in SCRAPER_TABLES]
    return HEADER + "".join("\n" + _create_table(t) for t in tables)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
            print(f"{OUTPUT} is out of date: run python scripts/export_scraper_schema.py")
            return 1
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
