apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-pod-log-reader
  labels:
    app.kubernetes.io/name: airflow
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
