apiVersion: v1
kind: Service
metadata:
  name: s3
  labels:
    app.kubernetes.io/name: s3
spec:
  selector:
    app.kubernetes.io/name: s3
  ports:
    - name: s3
      port: 4566
      targetPort: s3
