apiVersion: v1
kind: Service
metadata:
  name: scraper-api
  labels:
    app.kubernetes.io/name: scraper-api
spec:
  selector:
    app.kubernetes.io/name: scraper-api
  ports:
    - name: http
      port: 8080
      targetPort: http
