apiVersion: v1
kind: Service
metadata:
  name: temporal
  labels:
    app.kubernetes.io/name: temporal
spec:
  selector:
    app.kubernetes.io/name: temporal
  ports:
    - name: frontend
      port: 7233
      targetPort: frontend
