apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  labels:
    app.kubernetes.io/name: temporal-ui
spec:
  selector:
    app.kubernetes.io/name: temporal-ui
  ports:
    - name: http
      port: 8080
      targetPort: http
