"""Pydantic request/response schemas.

Bronze, reference (provinces, districts, local bodies) and Silver. Gold is still to come.
"""

from .base import ReadSchema, SchemaBase
from .bronze import (
    CrawledDocumentBase,
    CrawledDocumentCreate,
    CrawledDocumentRead,
    CrawlRunBase,
    CrawlRunCreate,
    CrawlRunFinish,
    CrawlRunRead,
    CrawlRunStats,
    DomainBase,
    DomainCreate,
    DomainRead,
    DomainUpdate,
    StoredFileBase,
    StoredFileCreate,
    StoredFileRead,
)
from .geography import (
    DistrictBase,
    DistrictCreate,
    DistrictRead,
    DistrictUpdate,
    LocalBodyBase,
    LocalBodyCreate,
    LocalBodyRead,
    LocalBodyUpdate,
    ProvinceBase,
    ProvinceCreate,
    ProvinceRead,
    ProvinceUpdate,
)
from .silver import (
    EntityBase,
    EntityCreate,
    EntityRead,
    PageEmbeddingBase,
    PageEmbeddingCreate,
    PageEmbeddingRead,
    PageEntityBase,
    PageEntityCreate,
    PageEntityRead,
    PageMediaBase,
    PageMediaCreate,
    PageMediaRead,
    PageSourceRead,
    GeoLocationOut,
    PageBase,
    PageContactBase,
    PageContactCreate,
    PageContactRead,
    PageCreate,
    PageGeoTagBase,
    PageGeoTagCreate,
    PageGeoTagRead,
    PageRead,
    PageWithRelations,
)

__all__ = [
    "ReadSchema",
    "SchemaBase",
    # bronze - domains
    "DomainBase",
    "DomainCreate",
    "DomainRead",
    "DomainUpdate",
    # bronze - crawl runs
    "CrawlRunBase",
    "CrawlRunCreate",
    "CrawlRunFinish",
    "CrawlRunRead",
    "CrawlRunStats",
    # bronze - documents
    "CrawledDocumentBase",
    "CrawledDocumentCreate",
    "CrawledDocumentRead",
    # bronze - stored files
    "StoredFileBase",
    "StoredFileCreate",
    "StoredFileRead",
    # silver
    "PageBase",
    "PageCreate",
    "PageRead",
    "PageWithRelations",
    "PageGeoTagBase",
    "PageGeoTagCreate",
    "PageGeoTagRead",
    "PageContactBase",
    "PageContactCreate",
    "PageContactRead",
    "GeoLocationOut",
    "EntityBase",
    "EntityCreate",
    "EntityRead",
    "PageEmbeddingBase",
    "PageEmbeddingCreate",
    "PageEmbeddingRead",
    "PageEntityBase",
    "PageEntityCreate",
    "PageEntityRead",
    "PageMediaBase",
    "PageMediaCreate",
    "PageMediaRead",
    "PageSourceRead",
    # geography
    "ProvinceBase",
    "ProvinceCreate",
    "ProvinceRead",
    "ProvinceUpdate",
    "DistrictBase",
    "DistrictCreate",
    "DistrictRead",
    "DistrictUpdate",
    "LocalBodyBase",
    "LocalBodyCreate",
    "LocalBodyRead",
    "LocalBodyUpdate",
]
