"""Pydantic request/response schemas.

Bronze, reference (provinces, districts, local bodies), Silver, Gold and ops (admin users,
error logs).
"""

from .base import ReadSchema, SchemaBase
from .bronze import (
    CrawledDocumentBase,
    CrawledDocumentCreate,
    CrawledDocumentRead,
    CrawlRunBase,
    CrawlRunCreate,
    CrawlRunFinish,
    CrawlRunRead,
    CrawlRunStats,
    DomainBase,
    DomainCreate,
    DomainRead,
    DomainUpdate,
    StoredFileBase,
    StoredFileCreate,
    StoredFileRead,
)
from .gold import (
    DashboardSummary,
    DomainCounts,
    DomainOverview,
    DomainStatsRead,
    ErrorCounts,
    GeoContentCount,
    PageScoreRead,
    RelevanceJudgmentCreate,
    RelevanceJudgmentRead,
    SearchClickCreate,
    SearchClickRead,
    SearchQueryCreate,
    SearchQueryRead,
    SearchTraffic,
    LinkCounts,
    StorageMetrics,
)
from .geography import (
    DistrictBase,
    DistrictCreate,
    DistrictRead,
    DistrictUpdate,
    LocalBodyBase,
    LocalBodyCreate,
    LocalBodyRead,
    LocalBodyUpdate,
    ProvinceBase,
    ProvinceCreate,
    ProvinceRead,
    ProvinceUpdate,
)
from .ops import (
    AdminUserCreate,
    AdminUserRead,
    AdminUserUpdate,
    ErrorLogCreate,
    ErrorLogRead,
)
from .search import (
    DistrictNode,
    FileInfo,
    LocalBodyNode,
    ProvinceNode,
    QuickLink,
    RegionalCard,
    RegionContact,
    RegionLinkCreate,
    RegionLinkRead,
    RegionRef,
    SearchDocumentOut,
    VectorHit,
)
from .silver import (
    QuarantinedFileRead,
    QuarantineSummary,
    EntityBase,
    EntityCreate,
    EntityRead,
    PageEmbeddingBase,
    PageEmbeddingCreate,
    PageEmbeddingRead,
    PageEntityBase,
    PageEntityCreate,
    PageEntityRead,
    PageMediaBase,
    PageMediaCreate,
    PageMediaRead,
    PageSourceRead,
    GeoLocationOut,
    PageBase,
    PageContactBase,
    PageContactCreate,
    PageContactRead,
    PageCreate,
    PageGeoTagBase,
    PageGeoTagCreate,
    PageGeoTagRead,
    PageRead,
    PageWithRelations,
)

__all__ = [
    "ReadSchema",
    "SchemaBase",
    # bronze - domains
    "DomainBase",
    "DomainCreate",
    "DomainRead",
    "DomainUpdate",
    # bronze - crawl runs
    "CrawlRunBase",
    "CrawlRunCreate",
    "CrawlRunFinish",
    "CrawlRunRead",
    "CrawlRunStats",
    # bronze - documents
    "CrawledDocumentBase",
    "CrawledDocumentCreate",
    "CrawledDocumentRead",
    # bronze - stored files
    "StoredFileBase",
    "StoredFileCreate",
    "StoredFileRead",
    # silver
    "PageBase",
    "PageCreate",
    "PageRead",
    "PageWithRelations",
    "PageGeoTagBase",
    "PageGeoTagCreate",
    "PageGeoTagRead",
    "PageContactBase",
    "PageContactCreate",
    "PageContactRead",
    "GeoLocationOut",
    "EntityBase",
    "EntityCreate",
    "EntityRead",
    "PageEmbeddingBase",
    "PageEmbeddingCreate",
    "PageEmbeddingRead",
    "PageEntityBase",
    "PageEntityCreate",
    "PageEntityRead",
    "PageMediaBase",
    "PageMediaCreate",
    "PageMediaRead",
    "PageSourceRead",
    "QuarantinedFileRead",
    "QuarantineSummary",
    # geography
    "ProvinceBase",
    "ProvinceCreate",
    "ProvinceRead",
    "ProvinceUpdate",
    "DistrictBase",
    "DistrictCreate",
    "DistrictRead",
    "DistrictUpdate",
    "LocalBodyBase",
    "LocalBodyCreate",
    "LocalBodyRead",
    "LocalBodyUpdate",
    # gold
    "DomainStatsRead",
    "DomainOverview",
    "DomainCounts",
    "LinkCounts",
    "StorageMetrics",
    "ErrorCounts",
    "DashboardSummary",
    "GeoContentCount",
    "PageScoreRead",
    "RelevanceJudgmentCreate",
    "RelevanceJudgmentRead",
    "SearchClickCreate",
    "SearchClickRead",
    "SearchQueryCreate",
    "SearchQueryRead",
    "SearchTraffic",
    # search, map and regional card
    "SearchDocumentOut",
    "FileInfo",
    "VectorHit",
    "ProvinceNode",
    "DistrictNode",
    "LocalBodyNode",
    "RegionalCard",
    "RegionContact",
    "RegionRef",
    "QuickLink",
    "RegionLinkCreate",
    "RegionLinkRead",
    # ops
    "AdminUserCreate",
    "AdminUserUpdate",
    "AdminUserRead",
    "ErrorLogCreate",
    "ErrorLogRead",
]
