// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CrawlRun struct {
	Category           pgtype.Text        `json:"category"`
	Status             string             `json:"status"`
	TemporalWorkflowID pgtype.Text        `json:"temporal_workflow_id"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
	SeedCount          pgtype.Int4        `json:"seed_count"`
	MaxDepth           pgtype.Int4        `json:"max_depth"`
	MaxPages           pgtype.Int4        `json:"max_pages"`
	FetchedCount       int32              `json:"fetched_count"`
	SucceededCount     int32              `json:"succeeded_count"`
	FailedCount        int32              `json:"failed_count"`
	SkippedCount       int32              `json:"skipped_count"`
	UniqueUrlCount     int32              `json:"unique_url_count"`
	DomainCappedCount  int32              `json:"domain_capped_count"`
	Error              pgtype.Text        `json:"error"`
	ID                 int64              `json:"id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type CrawledDocument struct {
	CrawlRunID       pgtype.Int8        `json:"crawl_run_id"`
	DomainID         pgtype.Int8        `json:"domain_id"`
	Url              string             `json:"url"`
	NormalizedUrl    string             `json:"normalized_url"`
	FinalUrl         pgtype.Text        `json:"final_url"`
	CanonicalUrl     pgtype.Text        `json:"canonical_url"`
	Host             pgtype.Text        `json:"host"`
	Category         pgtype.Text        `json:"category"`
	Title            pgtype.Text        `json:"title"`
	MetaDescription  pgtype.Text        `json:"meta_description"`
	MetaKeywords     []string           `json:"meta_keywords"`
	OpenGraph        []byte             `json:"open_graph"`
	Text             pgtype.Text        `json:"text"`
	Headings         []byte             `json:"headings"`
	JsonLd           []string           `json:"json_ld"`
	Emails           []string           `json:"emails"`
	Phones           []string           `json:"phones"`
	Address          pgtype.Text        `json:"address"`
	SocialLinks      []string           `json:"social_links"`
	Links            []string           `json:"links"`
	AnchorTexts      []string           `json:"anchor_texts"`
	InternalLinks    []string           `json:"internal_links"`
	ExternalLinks    []string           `json:"external_links"`
	ImageLinks       []string           `json:"image_links"`
	VideoLinks       []string           `json:"video_links"`
	GeoLat           pgtype.Float8      `json:"geo_lat"`
	GeoLng           pgtype.Float8      `json:"geo_lng"`
	Country          pgtype.Text        `json:"country"`
	SimHash          pgtype.Int8        `json:"sim_hash"`
	Depth            int32              `json:"depth"`
	StatusCode       pgtype.Int4        `json:"status_code"`
	ContentType      pgtype.Text        `json:"content_type"`
	ContentHash      string             `json:"content_hash"`
	FetchedAt        pgtype.Timestamptz `json:"fetched_at"`
	FetchDurationMs  pgtype.Int8        `json:"fetch_duration_ms"`
	Error            pgtype.Text        `json:"error"`
	MinioPath        pgtype.Text        `json:"minio_path"`
	ProcessingStatus string             `json:"processing_status"`
	ProcessingError  pgtype.Text        `json:"processing_error"`
	ID               int64              `json:"id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Domain struct {
	Domain          string             `json:"domain"`
	WebsiteName     pgtype.Text        `json:"website_name"`
	Category        string             `json:"category"`
	Status          string             `json:"status"`
	Priority        string             `json:"priority"`
	RateLimitPerSec int32              `json:"rate_limit_per_sec"`
	LocalBodyID     pgtype.Int8        `json:"local_body_id"`
	LastCrawledAt   pgtype.Timestamptz `json:"last_crawled_at"`
	ID              int64              `json:"id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type StoredFile struct {
	CrawledDocumentID pgtype.Int8        `json:"crawled_document_id"`
	SourcePageUrl     string             `json:"source_page_url"`
	DocumentUrl       string             `json:"document_url"`
	StoragePath       string             `json:"storage_path"`
	ContentType       pgtype.Text        `json:"content_type"`
	Sha256            string             `json:"sha256"`
	SizeBytes         int64              `json:"size_bytes"`
	StoredAt          pgtype.Timestamptz `json:"stored_at"`
	ProcessingStatus  string             `json:"processing_status"`
	ProcessingError   pgtype.Text        `json:"processing_error"`
	ID                int64              `json:"id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
