// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CrawlRun struct {
	ID           int64              `json:"id"`
	Status       string             `json:"status"`
	SeedCount    int32              `json:"seed_count"`
	MaxDepth     int32              `json:"max_depth"`
	MaxPages     int32              `json:"max_pages"`
	Fetched      int32              `json:"fetched"`
	Succeeded    int32              `json:"succeeded"`
	Failed       int32              `json:"failed"`
	Skipped      int32              `json:"skipped"`
	DomainCapped int32              `json:"domain_capped"`
	Error        string             `json:"error"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Document struct {
	ID              int64              `json:"id"`
	Url             string             `json:"url"`
	NormalizedUrl   string             `json:"normalized_url"`
	Category        string             `json:"category"`
	Title           string             `json:"title"`
	BodyText        string             `json:"body_text"`
	Links           []string           `json:"links"`
	Depth           int32              `json:"depth"`
	StatusCode      int32              `json:"status_code"`
	ContentType     string             `json:"content_type"`
	ContentHash     string             `json:"content_hash"`
	FetchDurationMs int64              `json:"fetch_duration_ms"`
	FetchError      string             `json:"fetch_error"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	JsonLd          []string           `json:"json_ld"`
	GeoLat          pgtype.Float8      `json:"geo_lat"`
	GeoLng          pgtype.Float8      `json:"geo_lng"`
	AnchorTexts     []string           `json:"anchor_texts"`
	CrawlRunID      pgtype.Int8        `json:"crawl_run_id"`
	CanonicalUrl    string             `json:"canonical_url"`
	FinalUrl        string             `json:"final_url"`
	SimHash         int64              `json:"sim_hash"`
	MetaDescription string             `json:"meta_description"`
	Headings        []byte             `json:"headings"`
	Host            string             `json:"host"`
	Country         string             `json:"country"`
}
