// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountDocuments(ctx context.Context) (int64, error)
	CountDocumentsByCategory(ctx context.Context) ([]CountDocumentsByCategoryRow, error)
	CreateCrawlRun(ctx context.Context, arg CreateCrawlRunParams) (int64, error)
	FinishCrawlRun(ctx context.Context, arg FinishCrawlRunParams) error
	GetCrawlRun(ctx context.Context, id int64) (CrawlRun, error)
	ListCrawlRuns(ctx context.Context, arg ListCrawlRunsParams) ([]CrawlRun, error)
	// crawl_run_id and country are optional additional filters: pass NULL to
	// ignore either (all documents in the category), or a specific run's ID /
	// ISO 3166-1 alpha-2 country code to narrow further -- e.g. an ETL
	// consumer scoped to only Nepal-origin documents (country = 'NP').
	ListDocumentsByCategory(ctx context.Context, arg ListDocumentsByCategoryParams) ([]Document, error)
	// Given a batch of candidate normalized URLs, returns the subset that
	// already have a document fetched more recently than `since` -- the
	// revisit/freshness policy's core check: skip re-fetching a URL that was
	// crawled recently enough, but allow one that's stale or was never crawled
	// (never crawled simply won't appear in the result, which is what
	// "startable" means to the caller).
	ListFreshDocumentURLs(ctx context.Context, arg ListFreshDocumentURLsParams) ([]string, error)
	// Called after every page processed within a run (including mid-run, before
	// Continue-As-New) so a run's progress is visible while it's still going,
	// not just after it finishes.
	UpdateCrawlRunStats(ctx context.Context, arg UpdateCrawlRunStatsParams) error
	// Idempotent write: a retried WriteDocument activity (Temporal at-least-once
	// semantics) lands on the same row instead of inserting a duplicate,
	// because normalized_url is unique -- one row per URL, always reflecting
	// its most recently crawled state. A retry with unchanged content is a
	// no-op update; a genuinely changed page (recrawled after RevisitAfter,
	// see CheckFreshness) has its fields refreshed in place rather than
	// accumulating a second row for the same URL.
	UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
