// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDocuments = `-- name: CountDocuments :one
SELECT count(*) FROM documents
`

func (q *Queries) CountDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsByCategory = `-- name: CountDocumentsByCategory :many
SELECT category, count(*) AS total FROM documents GROUP BY category ORDER BY category
`

type CountDocumentsByCategoryRow struct {
	Category string `json:"category"`
	Total    int64  `json:"total"`
}

func (q *Queries) CountDocumentsByCategory(ctx context.Context) ([]CountDocumentsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countDocumentsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDocumentsByCategoryRow
	for rows.Next() {
		var i CountDocumentsByCategoryRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCrawlRun = `-- name: CreateCrawlRun :one
INSERT INTO crawl_runs (seed_count, max_depth, max_pages)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateCrawlRunParams struct {
	SeedCount int32 `json:"seed_count"`
	MaxDepth  int32 `json:"max_depth"`
	MaxPages  int32 `json:"max_pages"`
}

func (q *Queries) CreateCrawlRun(ctx context.Context, arg CreateCrawlRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCrawlRun, arg.SeedCount, arg.MaxDepth, arg.MaxPages)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const finishCrawlRun = `-- name: FinishCrawlRun :exec
UPDATE crawl_runs SET
    status        = $2,
    fetched       = $3,
    succeeded     = $4,
    failed        = $5,
    skipped       = $6,
    domain_capped = $7,
    error         = $8,
    finished_at   = now(),
    updated_at    = now()
WHERE id = $1
`

type FinishCrawlRunParams struct {
	ID           int64  `json:"id"`
	Status       string `json:"status"`
	Fetched      int32  `json:"fetched"`
	Succeeded    int32  `json:"succeeded"`
	Failed       int32  `json:"failed"`
	Skipped      int32  `json:"skipped"`
	DomainCapped int32  `json:"domain_capped"`
	Error        string `json:"error"`
}

func (q *Queries) FinishCrawlRun(ctx context.Context, arg FinishCrawlRunParams) error {
	_, err := q.db.Exec(ctx, finishCrawlRun,
		arg.ID,
		arg.Status,
		arg.Fetched,
		arg.Succeeded,
		arg.Failed,
		arg.Skipped,
		arg.DomainCapped,
		arg.Error,
	)
	return err
}

const getCrawlRun = `-- name: GetCrawlRun :one
SELECT id, status, seed_count, max_depth, max_pages, fetched, succeeded, failed, skipped, domain_capped, error, started_at, finished_at, updated_at FROM crawl_runs WHERE id = $1
`

func (q *Queries) GetCrawlRun(ctx context.Context, id int64) (CrawlRun, error) {
	row := q.db.QueryRow(ctx, getCrawlRun, id)
	var i CrawlRun
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SeedCount,
		&i.MaxDepth,
		&i.MaxPages,
		&i.Fetched,
		&i.Succeeded,
		&i.Failed,
		&i.Skipped,
		&i.DomainCapped,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCrawlRuns = `-- name: ListCrawlRuns :many
SELECT id, status, seed_count, max_depth, max_pages, fetched, succeeded, failed, skipped, domain_capped, error, started_at, finished_at, updated_at FROM crawl_runs ORDER BY started_at DESC LIMIT $1 OFFSET $2
`

type ListCrawlRunsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCrawlRuns(ctx context.Context, arg ListCrawlRunsParams) ([]CrawlRun, error) {
	rows, err := q.db.Query(ctx, listCrawlRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrawlRun
	for rows.Next() {
		var i CrawlRun
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.SeedCount,
			&i.MaxDepth,
			&i.MaxPages,
			&i.Fetched,
			&i.Succeeded,
			&i.Failed,
			&i.Skipped,
			&i.DomainCapped,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByCategory = `-- name: ListDocumentsByCategory :many
SELECT id, url, normalized_url, category, title, body_text, links, depth, status_code, content_type, content_hash, fetch_duration_ms, fetch_error, fetched_at, created_at, updated_at, json_ld, geo_lat, geo_lng, anchor_texts, crawl_run_id, canonical_url, final_url, sim_hash, meta_description, headings, host, country FROM documents
WHERE category = $1
  AND ($4::bigint IS NULL OR crawl_run_id = $4)
  AND ($5::text IS NULL OR country = $5)
ORDER BY fetched_at DESC LIMIT $2 OFFSET $3
`

type ListDocumentsByCategoryParams struct {
	Category   string      `json:"category"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	CrawlRunID pgtype.Int8 `json:"crawl_run_id"`
	Country    pgtype.Text `json:"country"`
}

// crawl_run_id and country are optional additional filters: pass NULL to
// ignore either (all documents in the category), or a specific run's ID /
// ISO 3166-1 alpha-2 country code to narrow further -- e.g. an ETL
// consumer scoped to only Nepal-origin documents (country = 'NP').
func (q *Queries) ListDocumentsByCategory(ctx context.Context, arg ListDocumentsByCategoryParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByCategory,
		arg.Category,
		arg.Limit,
		arg.Offset,
		arg.CrawlRunID,
		arg.Country,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.NormalizedUrl,
			&i.Category,
			&i.Title,
			&i.BodyText,
			&i.Links,
			&i.Depth,
			&i.StatusCode,
			&i.ContentType,
			&i.ContentHash,
			&i.FetchDurationMs,
			&i.FetchError,
			&i.FetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JsonLd,
			&i.GeoLat,
			&i.GeoLng,
			&i.AnchorTexts,
			&i.CrawlRunID,
			&i.CanonicalUrl,
			&i.FinalUrl,
			&i.SimHash,
			&i.MetaDescription,
			&i.Headings,
			&i.Host,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFreshDocumentURLs = `-- name: ListFreshDocumentURLs :many
SELECT normalized_url FROM documents
WHERE normalized_url = ANY($1::text[])
  AND fetched_at > $2::timestamptz
`

type ListFreshDocumentURLsParams struct {
	NormalizedUrls []string           `json:"normalized_urls"`
	Since          pgtype.Timestamptz `json:"since"`
}

// Given a batch of candidate normalized URLs, returns the subset that
// already have a document fetched more recently than `since` -- the
// revisit/freshness policy's core check: skip re-fetching a URL that was
// crawled recently enough, but allow one that's stale or was never crawled
// (never crawled simply won't appear in the result, which is what
// "startable" means to the caller).
func (q *Queries) ListFreshDocumentURLs(ctx context.Context, arg ListFreshDocumentURLsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listFreshDocumentURLs, arg.NormalizedUrls, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var normalized_url string
		if err := rows.Scan(&normalized_url); err != nil {
			return nil, err
		}
		items = append(items, normalized_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCrawlRunStats = `-- name: UpdateCrawlRunStats :exec
UPDATE crawl_runs SET
    fetched       = $2,
    succeeded     = $3,
    failed        = $4,
    skipped       = $5,
    domain_capped = $6,
    updated_at    = now()
WHERE id = $1
`

type UpdateCrawlRunStatsParams struct {
	ID           int64 `json:"id"`
	Fetched      int32 `json:"fetched"`
	Succeeded    int32 `json:"succeeded"`
	Failed       int32 `json:"failed"`
	Skipped      int32 `json:"skipped"`
	DomainCapped int32 `json:"domain_capped"`
}

// Called after every page processed within a run (including mid-run, before
// Continue-As-New) so a run's progress is visible while it's still going,
// not just after it finishes.
func (q *Queries) UpdateCrawlRunStats(ctx context.Context, arg UpdateCrawlRunStatsParams) error {
	_, err := q.db.Exec(ctx, updateCrawlRunStats,
		arg.ID,
		arg.Fetched,
		arg.Succeeded,
		arg.Failed,
		arg.Skipped,
		arg.DomainCapped,
	)
	return err
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO documents (
    url, normalized_url, category, title, body_text, links, depth,
    status_code, content_type, content_hash, fetch_duration_ms, fetch_error,
    fetched_at, json_ld, geo_lat, geo_lng, anchor_texts, crawl_run_id,
    canonical_url, final_url, sim_hash, meta_description, headings, host,
    country
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25
)
ON CONFLICT (normalized_url) DO UPDATE SET
    url               = EXCLUDED.url,
    category          = EXCLUDED.category,
    title             = EXCLUDED.title,
    body_text         = EXCLUDED.body_text,
    links             = EXCLUDED.links,
    depth             = EXCLUDED.depth,
    status_code       = EXCLUDED.status_code,
    content_type      = EXCLUDED.content_type,
    content_hash      = EXCLUDED.content_hash,
    fetch_duration_ms = EXCLUDED.fetch_duration_ms,
    fetch_error       = EXCLUDED.fetch_error,
    fetched_at        = EXCLUDED.fetched_at,
    json_ld           = EXCLUDED.json_ld,
    geo_lat           = EXCLUDED.geo_lat,
    geo_lng           = EXCLUDED.geo_lng,
    anchor_texts      = EXCLUDED.anchor_texts,
    crawl_run_id      = EXCLUDED.crawl_run_id,
    canonical_url     = EXCLUDED.canonical_url,
    final_url         = EXCLUDED.final_url,
    sim_hash          = EXCLUDED.sim_hash,
    meta_description  = EXCLUDED.meta_description,
    headings          = EXCLUDED.headings,
    host              = EXCLUDED.host,
    country           = EXCLUDED.country,
    updated_at        = now()
RETURNING id
`

type UpsertDocumentParams struct {
	Url             string             `json:"url"`
	NormalizedUrl   string             `json:"normalized_url"`
	Category        string             `json:"category"`
	Title           string             `json:"title"`
	BodyText        string             `json:"body_text"`
	Links           []string           `json:"links"`
	Depth           int32              `json:"depth"`
	StatusCode      int32              `json:"status_code"`
	ContentType     string             `json:"content_type"`
	ContentHash     string             `json:"content_hash"`
	FetchDurationMs int64              `json:"fetch_duration_ms"`
	FetchError      string             `json:"fetch_error"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	JsonLd          []string           `json:"json_ld"`
	GeoLat          pgtype.Float8      `json:"geo_lat"`
	GeoLng          pgtype.Float8      `json:"geo_lng"`
	AnchorTexts     []string           `json:"anchor_texts"`
	CrawlRunID      pgtype.Int8        `json:"crawl_run_id"`
	CanonicalUrl    string             `json:"canonical_url"`
	FinalUrl        string             `json:"final_url"`
	SimHash         int64              `json:"sim_hash"`
	MetaDescription string             `json:"meta_description"`
	Headings        []byte             `json:"headings"`
	Host            string             `json:"host"`
	Country         string             `json:"country"`
}

// Idempotent write: a retried WriteDocument activity (Temporal at-least-once
// semantics) lands on the same row instead of inserting a duplicate,
// because normalized_url is unique -- one row per URL, always reflecting
// its most recently crawled state. A retry with unchanged content is a
// no-op update; a genuinely changed page (recrawled after RevisitAfter,
// see CheckFreshness) has its fields refreshed in place rather than
// accumulating a second row for the same URL.
func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDocument,
		arg.Url,
		arg.NormalizedUrl,
		arg.Category,
		arg.Title,
		arg.BodyText,
		arg.Links,
		arg.Depth,
		arg.StatusCode,
		arg.ContentType,
		arg.ContentHash,
		arg.FetchDurationMs,
		arg.FetchError,
		arg.FetchedAt,
		arg.JsonLd,
		arg.GeoLat,
		arg.GeoLng,
		arg.AnchorTexts,
		arg.CrawlRunID,
		arg.CanonicalUrl,
		arg.FinalUrl,
		arg.SimHash,
		arg.MetaDescription,
		arg.Headings,
		arg.Host,
		arg.Country,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
