// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDocuments = `-- name: CountDocuments :one
SELECT count(*) FROM crawled_documents
`

func (q *Queries) CountDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsByCategory = `-- name: CountDocumentsByCategory :many
SELECT coalesce(category, '')::text AS category, count(*) AS total
FROM crawled_documents GROUP BY 1 ORDER BY 1
`

type CountDocumentsByCategoryRow struct {
	Category string `json:"category"`
	Total    int64  `json:"total"`
}

func (q *Queries) CountDocumentsByCategory(ctx context.Context) ([]CountDocumentsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countDocumentsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDocumentsByCategoryRow
	for rows.Next() {
		var i CountDocumentsByCategoryRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCrawlRun = `-- name: CreateCrawlRun :one
INSERT INTO crawl_runs (
    status, started_at, seed_count, max_depth, max_pages,
    fetched_count, succeeded_count, failed_count, skipped_count, unique_url_count
) VALUES ('RUNNING', now(), $1, $2, $3, 0, 0, 0, 0, 0)
RETURNING id
`

type CreateCrawlRunParams struct {
	SeedCount pgtype.Int4 `json:"seed_count"`
	MaxDepth  pgtype.Int4 `json:"max_depth"`
	MaxPages  pgtype.Int4 `json:"max_pages"`
}

func (q *Queries) CreateCrawlRun(ctx context.Context, arg CreateCrawlRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCrawlRun, arg.SeedCount, arg.MaxDepth, arg.MaxPages)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const finishCrawlRun = `-- name: FinishCrawlRun :exec
UPDATE crawl_runs SET
    status              = $1,
    fetched_count       = $2,
    succeeded_count     = $3,
    failed_count        = $4,
    skipped_count       = $5,
    domain_capped_count = $6,
    error               = $7,
    finished_at         = now()
WHERE id = $8
`

type FinishCrawlRunParams struct {
	Status            string      `json:"status"`
	FetchedCount      int32       `json:"fetched_count"`
	SucceededCount    int32       `json:"succeeded_count"`
	FailedCount       int32       `json:"failed_count"`
	SkippedCount      int32       `json:"skipped_count"`
	DomainCappedCount int32       `json:"domain_capped_count"`
	Error             pgtype.Text `json:"error"`
	ID                int64       `json:"id"`
}

// status is 'completed' or 'failed' (any case; a trigger upper-cases it). error is
// NULL for a run that completed.
func (q *Queries) FinishCrawlRun(ctx context.Context, arg FinishCrawlRunParams) error {
	_, err := q.db.Exec(ctx, finishCrawlRun,
		arg.Status,
		arg.FetchedCount,
		arg.SucceededCount,
		arg.FailedCount,
		arg.SkippedCount,
		arg.DomainCappedCount,
		arg.Error,
		arg.ID,
	)
	return err
}

const getCrawlRun = `-- name: GetCrawlRun :one
SELECT category, status, temporal_workflow_id, started_at, finished_at, seed_count, max_depth, max_pages, fetched_count, succeeded_count, failed_count, skipped_count, unique_url_count, domain_capped_count, error, id, created_at, updated_at FROM crawl_runs WHERE id = $1
`

func (q *Queries) GetCrawlRun(ctx context.Context, id int64) (CrawlRun, error) {
	row := q.db.QueryRow(ctx, getCrawlRun, id)
	var i CrawlRun
	err := row.Scan(
		&i.Category,
		&i.Status,
		&i.TemporalWorkflowID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SeedCount,
		&i.MaxDepth,
		&i.MaxPages,
		&i.FetchedCount,
		&i.SucceededCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.UniqueUrlCount,
		&i.DomainCappedCount,
		&i.Error,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCrawlRuns = `-- name: ListCrawlRuns :many
SELECT category, status, temporal_workflow_id, started_at, finished_at, seed_count, max_depth, max_pages, fetched_count, succeeded_count, failed_count, skipped_count, unique_url_count, domain_capped_count, error, id, created_at, updated_at FROM crawl_runs ORDER BY started_at DESC LIMIT $1 OFFSET $2
`

type ListCrawlRunsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCrawlRuns(ctx context.Context, arg ListCrawlRunsParams) ([]CrawlRun, error) {
	rows, err := q.db.Query(ctx, listCrawlRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrawlRun
	for rows.Next() {
		var i CrawlRun
		if err := rows.Scan(
			&i.Category,
			&i.Status,
			&i.TemporalWorkflowID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.SeedCount,
			&i.MaxDepth,
			&i.MaxPages,
			&i.FetchedCount,
			&i.SucceededCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.UniqueUrlCount,
			&i.DomainCappedCount,
			&i.Error,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByCategory = `-- name: ListDocumentsByCategory :many
SELECT crawl_run_id, domain_id, url, normalized_url, final_url, canonical_url, host, category, title, meta_description, meta_keywords, open_graph, text, headings, json_ld, emails, phones, address, social_links, links, anchor_texts, internal_links, external_links, image_links, video_links, geo_lat, geo_lng, country, sim_hash, depth, status_code, content_type, content_hash, fetched_at, fetch_duration_ms, error, minio_path, processing_status, processing_error, id, created_at, updated_at FROM crawled_documents
WHERE category = $1::text
  AND ($2::bigint IS NULL OR crawl_run_id = $2)
  AND ($3::text IS NULL OR country = $3)
ORDER BY fetched_at DESC LIMIT $5 OFFSET $4
`

type ListDocumentsByCategoryParams struct {
	Category   string      `json:"category"`
	CrawlRunID pgtype.Int8 `json:"crawl_run_id"`
	Country    pgtype.Text `json:"country"`
	Offset     int32       `json:"offset"`
	Limit      int32       `json:"limit"`
}

// crawl_run_id and country are optional filters: NULL ignores them.
func (q *Queries) ListDocumentsByCategory(ctx context.Context, arg ListDocumentsByCategoryParams) ([]CrawledDocument, error) {
	rows, err := q.db.Query(ctx, listDocumentsByCategory,
		arg.Category,
		arg.CrawlRunID,
		arg.Country,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrawledDocument
	for rows.Next() {
		var i CrawledDocument
		if err := rows.Scan(
			&i.CrawlRunID,
			&i.DomainID,
			&i.Url,
			&i.NormalizedUrl,
			&i.FinalUrl,
			&i.CanonicalUrl,
			&i.Host,
			&i.Category,
			&i.Title,
			&i.MetaDescription,
			&i.MetaKeywords,
			&i.OpenGraph,
			&i.Text,
			&i.Headings,
			&i.JsonLd,
			&i.Emails,
			&i.Phones,
			&i.Address,
			&i.SocialLinks,
			&i.Links,
			&i.AnchorTexts,
			&i.InternalLinks,
			&i.ExternalLinks,
			&i.ImageLinks,
			&i.VideoLinks,
			&i.GeoLat,
			&i.GeoLng,
			&i.Country,
			&i.SimHash,
			&i.Depth,
			&i.StatusCode,
			&i.ContentType,
			&i.ContentHash,
			&i.FetchedAt,
			&i.FetchDurationMs,
			&i.Error,
			&i.MinioPath,
			&i.ProcessingStatus,
			&i.ProcessingError,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFreshDocumentURLs = `-- name: ListFreshDocumentURLs :many
SELECT DISTINCT normalized_url FROM crawled_documents
WHERE normalized_url = ANY($1::text[])
  AND fetched_at > $2::timestamptz
`

type ListFreshDocumentURLsParams struct {
	NormalizedUrls []string           `json:"normalized_urls"`
	Since          pgtype.Timestamptz `json:"since"`
}

// The subset of the candidate URLs with any version fetched after `since`: the
// revisit policy skips those; a URL never crawled simply isn't returned.
func (q *Queries) ListFreshDocumentURLs(ctx context.Context, arg ListFreshDocumentURLsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listFreshDocumentURLs, arg.NormalizedUrls, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var normalized_url string
		if err := rows.Scan(&normalized_url); err != nil {
			return nil, err
		}
		items = append(items, normalized_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCrawlRunStats = `-- name: UpdateCrawlRunStats :exec
UPDATE crawl_runs SET
    fetched_count       = $2,
    succeeded_count     = $3,
    failed_count        = $4,
    skipped_count       = $5,
    domain_capped_count = $6
WHERE id = $1
`

type UpdateCrawlRunStatsParams struct {
	ID                int64 `json:"id"`
	FetchedCount      int32 `json:"fetched_count"`
	SucceededCount    int32 `json:"succeeded_count"`
	FailedCount       int32 `json:"failed_count"`
	SkippedCount      int32 `json:"skipped_count"`
	DomainCappedCount int32 `json:"domain_capped_count"`
}

// Called during a run (including before a Continue-As-New), so a run's progress
// is visible while it is still going.
func (q *Queries) UpdateCrawlRunStats(ctx context.Context, arg UpdateCrawlRunStatsParams) error {
	_, err := q.db.Exec(ctx, updateCrawlRunStats,
		arg.ID,
		arg.FetchedCount,
		arg.SucceededCount,
		arg.FailedCount,
		arg.SkippedCount,
		arg.DomainCappedCount,
	)
	return err
}

const upsertCrawledDocument = `-- name: UpsertCrawledDocument :one

INSERT INTO crawled_documents (
    crawl_run_id, domain_id, url, normalized_url, final_url, canonical_url, host, category,
    title, meta_description, meta_keywords, open_graph, text, headings, json_ld,
    emails, phones, address, social_links, links, anchor_texts,
    internal_links, external_links, image_links, video_links,
    geo_lat, geo_lng, country, sim_hash, depth, status_code, content_type,
    content_hash, fetched_at, fetch_duration_ms, error
) VALUES (
    $1,
    (SELECT d.id FROM domains d WHERE d.domain = regexp_replace(lower($2::text), '^www\.', '')),
    $3, $4, $5, $6,
    $2, $7,
    $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20,
    $21, $22, $23,
    $24,
    $25, $26, $27, $28,
    $29, $30, $31,
    $32, $33, $34,
    $35
)
ON CONFLICT (normalized_url, content_hash) DO UPDATE SET
    crawl_run_id      = EXCLUDED.crawl_run_id,
    domain_id         = EXCLUDED.domain_id,
    url               = EXCLUDED.url,
    final_url         = EXCLUDED.final_url,
    canonical_url     = EXCLUDED.canonical_url,
    host              = EXCLUDED.host,
    category          = EXCLUDED.category,
    title             = EXCLUDED.title,
    meta_description  = EXCLUDED.meta_description,
    meta_keywords     = EXCLUDED.meta_keywords,
    open_graph        = EXCLUDED.open_graph,
    text              = EXCLUDED.text,
    headings          = EXCLUDED.headings,
    json_ld           = EXCLUDED.json_ld,
    emails            = EXCLUDED.emails,
    phones            = EXCLUDED.phones,
    address           = EXCLUDED.address,
    social_links      = EXCLUDED.social_links,
    links             = EXCLUDED.links,
    anchor_texts      = EXCLUDED.anchor_texts,
    internal_links    = EXCLUDED.internal_links,
    external_links    = EXCLUDED.external_links,
    image_links       = EXCLUDED.image_links,
    video_links       = EXCLUDED.video_links,
    geo_lat           = EXCLUDED.geo_lat,
    geo_lng           = EXCLUDED.geo_lng,
    country           = EXCLUDED.country,
    sim_hash          = EXCLUDED.sim_hash,
    depth             = EXCLUDED.depth,
    status_code       = EXCLUDED.status_code,
    content_type      = EXCLUDED.content_type,
    fetched_at        = EXCLUDED.fetched_at,
    fetch_duration_ms = EXCLUDED.fetch_duration_ms,
    error             = EXCLUDED.error
RETURNING id, (xmax = 0)::boolean AS inserted
`

type UpsertCrawledDocumentParams struct {
	CrawlRunID      pgtype.Int8        `json:"crawl_run_id"`
	Host            pgtype.Text        `json:"host"`
	Url             string             `json:"url"`
	NormalizedUrl   string             `json:"normalized_url"`
	FinalUrl        pgtype.Text        `json:"final_url"`
	CanonicalUrl    pgtype.Text        `json:"canonical_url"`
	Category        pgtype.Text        `json:"category"`
	Title           pgtype.Text        `json:"title"`
	MetaDescription pgtype.Text        `json:"meta_description"`
	MetaKeywords    []string           `json:"meta_keywords"`
	OpenGraph       []byte             `json:"open_graph"`
	Text            pgtype.Text        `json:"text"`
	Headings        []byte             `json:"headings"`
	JsonLd          []string           `json:"json_ld"`
	Emails          []string           `json:"emails"`
	Phones          []string           `json:"phones"`
	Address         pgtype.Text        `json:"address"`
	SocialLinks     []string           `json:"social_links"`
	Links           []string           `json:"links"`
	AnchorTexts     []string           `json:"anchor_texts"`
	InternalLinks   []string           `json:"internal_links"`
	ExternalLinks   []string           `json:"external_links"`
	ImageLinks      []string           `json:"image_links"`
	VideoLinks      []string           `json:"video_links"`
	GeoLat          pgtype.Float8      `json:"geo_lat"`
	GeoLng          pgtype.Float8      `json:"geo_lng"`
	Country         pgtype.Text        `json:"country"`
	SimHash         pgtype.Int8        `json:"sim_hash"`
	Depth           int32              `json:"depth"`
	StatusCode      pgtype.Int4        `json:"status_code"`
	ContentType     pgtype.Text        `json:"content_type"`
	ContentHash     string             `json:"content_hash"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	FetchDurationMs pgtype.Int8        `json:"fetch_duration_ms"`
	Error           pgtype.Text        `json:"error"`
}

type UpsertCrawledDocumentRow struct {
	ID       int64 `json:"id"`
	Inserted bool  `json:"inserted"`
}

// Queries against the shared schema, owned by database/ (pgs_db models + Alembic);
// sqlc reads it from database/sql/scraper_schema.sql, exported from those models. The writes are the statements of
// database/docs/scraper-db-contract.md.
// Keyed on (normalized_url, content_hash): a retried WriteDocument activity
// (Temporal at-least-once) or a re-crawl of unchanged content updates the same
// row; changed content adds a new version row. domain_id is resolved from the
// host, without www. (domains are stored that way, see pgs_db site_host); NULL for
// a host that isn't a registered domain -- the page still stores.
// inserted is true only for a genuinely new row.
func (q *Queries) UpsertCrawledDocument(ctx context.Context, arg UpsertCrawledDocumentParams) (UpsertCrawledDocumentRow, error) {
	row := q.db.QueryRow(ctx, upsertCrawledDocument,
		arg.CrawlRunID,
		arg.Host,
		arg.Url,
		arg.NormalizedUrl,
		arg.FinalUrl,
		arg.CanonicalUrl,
		arg.Category,
		arg.Title,
		arg.MetaDescription,
		arg.MetaKeywords,
		arg.OpenGraph,
		arg.Text,
		arg.Headings,
		arg.JsonLd,
		arg.Emails,
		arg.Phones,
		arg.Address,
		arg.SocialLinks,
		arg.Links,
		arg.AnchorTexts,
		arg.InternalLinks,
		arg.ExternalLinks,
		arg.ImageLinks,
		arg.VideoLinks,
		arg.GeoLat,
		arg.GeoLng,
		arg.Country,
		arg.SimHash,
		arg.Depth,
		arg.StatusCode,
		arg.ContentType,
		arg.ContentHash,
		arg.FetchedAt,
		arg.FetchDurationMs,
		arg.Error,
	)
	var i UpsertCrawledDocumentRow
	err := row.Scan(&i.ID, &i.Inserted)
	return i, err
}
