"""quarantined files

Revision ID: 8aa170eaaf03
Revises: ac08008a1fbf
Create Date: 2026-09-26 12:28:49.304611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# processing_status is one shared enum, so all three tables get the new value.
_STATUS_TABLES = ('crawled_documents', 'stored_files', 'pages')
_OLD_STATUSES = ('UNPROCESSED', 'PROCESSING', 'PROCESSED', 'FAILED')
_NEW_STATUSES = _OLD_STATUSES + ('QUARANTINED',)


def _set_status_check(values: tuple[str, ...]) -> None:
    allowed = ', '.join(f"'{v}'" for v in values)
    for table in _STATUS_TABLES:
        name = op.f(f'ck_{table}_processing_status')  # op.f: already the final name
        op.drop_constraint(name, table, type_='check')
        op.create_check_constraint(name, table, f'processing_status IN ({allowed})')


# revision identifiers, used by Alembic.
revision: str = '8aa170eaaf03'
down_revision: Union[str, Sequence[str], None] = 'ac08008a1fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarantined_files',
    sa.Column('crawled_document_id', sa.BigInteger(), nullable=True),
    sa.Column('stored_file_id', sa.BigInteger(), nullable=True),
    sa.Column('domain_id', sa.BigInteger(), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=False),
    sa.Column('source_page_url', sa.Text(), nullable=True),
    sa.Column('original_path', sa.Text(), nullable=True),
    sa.Column('quarantine_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('threat_signature', sa.Text(), nullable=False),
    sa.Column('scanner_engine', sa.String(length=64), nullable=False),
    sa.Column('scanner_version', sa.String(length=64), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('QUARANTINED', 'DELETED', name='quarantine_status', native_enum=False, create_constraint=True, length=32), server_default='QUARANTINED', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(crawled_document_id, stored_file_id) <= 1', name=op.f('ck_quarantined_files_at_most_one_source')),
    sa.CheckConstraint('size_bytes IS NULL OR size_bytes >= 0', name=op.f('ck_quarantined_files_size_non_negative')),
    sa.ForeignKeyConstraint(['crawled_document_id'], ['crawled_documents.id'], name=op.f('fk_quarantined_files_crawled_document_id_crawled_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_quarantined_files_domain_id_domains')),
    sa.ForeignKeyConstraint(['stored_file_id'], ['stored_files.id'], name=op.f('fk_quarantined_files_stored_file_id_stored_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quarantined_files')),
    sa.UniqueConstraint('document_url', 'sha256', name='uq_quarantined_files_document_url_sha256')
    )
    op.create_index(op.f('ix_quarantined_files_crawled_document_id'), 'quarantined_files', ['crawled_document_id'], unique=False)
    op.create_index(op.f('ix_quarantined_files_domain_id'), 'quarantined_files', ['domain_id'], unique=False)
    op.create_index(op.f('ix_quarantined_files_sha256'), 'quarantined_files', ['sha256'], unique=False)
    op.create_index('ix_quarantined_files_status_scanned_at', 'quarantined_files', ['status', 'scanned_at'], unique=False)
    op.create_index(op.f('ix_quarantined_files_stored_file_id'), 'quarantined_files', ['stored_file_id'], unique=False)
    # ### end Alembic commands ###
    # Autogenerate does not detect CHECK changes.
    _set_status_check(_NEW_STATUSES)


def downgrade() -> None:
    """Downgrade schema."""
    # Quarantined Bronze rows fall back to FAILED, the closest old status.
    for table in _STATUS_TABLES:
        op.execute(f"UPDATE {table} SET processing_status = 'FAILED' "
                   "WHERE processing_status = 'QUARANTINED'")
    _set_status_check(_OLD_STATUSES)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quarantined_files_stored_file_id'), table_name='quarantined_files')
    op.drop_index('ix_quarantined_files_status_scanned_at', table_name='quarantined_files')
    op.drop_index(op.f('ix_quarantined_files_sha256'), table_name='quarantined_files')
    op.drop_index(op.f('ix_quarantined_files_domain_id'), table_name='quarantined_files')
    op.drop_index(op.f('ix_quarantined_files_crawled_document_id'), table_name='quarantined_files')
    op.drop_table('quarantined_files')
    # ### end Alembic commands ###
