"""create silver layer tables

Revision ID: e529ca38e6ae
Revises: 95e7b8aa6ec5
Create Date: 2026-09-23 08:55:14.076552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e529ca38e6ae'
down_revision: Union[str, Sequence[str], None] = '95e7b8aa6ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawled_documents', sa.Column('processing_error', sa.Text(), nullable=True))
    op.create_table('pages',
    sa.Column('crawled_document_id', sa.BigInteger(), nullable=False),
    sa.Column('domain_id', sa.BigInteger(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('language', sa.Enum('NE', 'EN', 'MIXED', 'OTHER', name='language', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('sim_hash', sa.BigInteger(), nullable=True),
    sa.Column('duplicate_of_id', sa.BigInteger(), nullable=True),
    sa.Column('processing_status', sa.Enum('UNPROCESSED', 'PROCESSING', 'PROCESSED', 'FAILED', name='processing_status', native_enum=False, create_constraint=True, length=32), server_default='UNPROCESSED', nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawled_document_id'], ['crawled_documents.id'], name=op.f('fk_pages_crawled_document_id_crawled_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_pages_domain_id_domains')),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['pages.id'], name=op.f('fk_pages_duplicate_of_id_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pages')),
    sa.UniqueConstraint('canonical_url', name=op.f('uq_pages_canonical_url'))
    )
    op.create_index('ix_pages_content_hash', 'pages', ['content_hash'], unique=False)
    op.create_index(op.f('ix_pages_crawled_document_id'), 'pages', ['crawled_document_id'], unique=False)
    op.create_index(op.f('ix_pages_domain_id'), 'pages', ['domain_id'], unique=False)
    op.create_index(op.f('ix_pages_duplicate_of_id'), 'pages', ['duplicate_of_id'], unique=False)
    op.create_index('ix_pages_processing_status', 'pages', ['processing_status'], unique=False)
    op.create_index('ix_pages_published_at', 'pages', ['published_at'], unique=False)
    op.create_table('page_contacts',
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('EMAIL', 'PHONE', 'SOCIAL', name='contact_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_page_contacts_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_contacts')),
    sa.UniqueConstraint('page_id', 'type', 'value', name='uq_page_contacts_page_type_value')
    )
    op.create_index(op.f('ix_page_contacts_page_id'), 'page_contacts', ['page_id'], unique=False)
    op.create_index('ix_page_contacts_type_value', 'page_contacts', ['type', 'value'], unique=False)
    op.create_table('page_geo_tags',
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('province_code', sa.String(length=4), nullable=True),
    sa.Column('district_code', sa.String(length=4), nullable=True),
    sa.Column('local_body_code', sa.String(length=16), nullable=True),
    sa.Column('ward_number', sa.Integer(), nullable=True),
    sa.Column('method', sa.Enum('GAZETTEER', 'NER', 'DOMAIN', 'GEO_META', name='geo_tag_method', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mention_text', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_page_geo_tags_confidence_range')),
    sa.CheckConstraint('province_code IS NOT NULL OR district_code IS NOT NULL OR local_body_code IS NOT NULL', name=op.f('ck_page_geo_tags_at_least_one_level')),
    sa.CheckConstraint('ward_number IS NULL OR ward_number > 0', name=op.f('ck_page_geo_tags_ward_number_positive')),
    sa.ForeignKeyConstraint(['district_code'], ['districts.code'], name=op.f('fk_page_geo_tags_district_code_districts')),
    sa.ForeignKeyConstraint(['local_body_code'], ['local_bodies.code'], name=op.f('fk_page_geo_tags_local_body_code_local_bodies')),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_page_geo_tags_page_id_pages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_code'], ['provinces.code'], name=op.f('fk_page_geo_tags_province_code_provinces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_geo_tags')),
    sa.UniqueConstraint('page_id', 'province_code', 'district_code', 'local_body_code', 'ward_number', name='uq_page_geo_tags_page_location', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_page_geo_tags_district_code', 'page_geo_tags', ['district_code'], unique=False)
    op.create_index('ix_page_geo_tags_local_body_code', 'page_geo_tags', ['local_body_code'], unique=False)
    op.create_index(op.f('ix_page_geo_tags_page_id'), 'page_geo_tags', ['page_id'], unique=False)
    op.create_index('ix_page_geo_tags_province_code', 'page_geo_tags', ['province_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_page_geo_tags_province_code', table_name='page_geo_tags')
    op.drop_index(op.f('ix_page_geo_tags_page_id'), table_name='page_geo_tags')
    op.drop_index('ix_page_geo_tags_local_body_code', table_name='page_geo_tags')
    op.drop_index('ix_page_geo_tags_district_code', table_name='page_geo_tags')
    op.drop_table('page_geo_tags')
    op.drop_index('ix_page_contacts_type_value', table_name='page_contacts')
    op.drop_index(op.f('ix_page_contacts_page_id'), table_name='page_contacts')
    op.drop_table('page_contacts')
    op.drop_index('ix_pages_published_at', table_name='pages')
    op.drop_index('ix_pages_processing_status', table_name='pages')
    op.drop_index(op.f('ix_pages_duplicate_of_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_domain_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_crawled_document_id'), table_name='pages')
    op.drop_index('ix_pages_content_hash', table_name='pages')
    op.drop_table('pages')
    op.drop_column('crawled_documents', 'processing_error')
    # ### end Alembic commands ###
