"""complete silver layer

Revision ID: ac08008a1fbf
Revises: e6aa9e30d49a
Create Date: 2026-09-26 11:49:06.747509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac08008a1fbf'
down_revision: Union[str, Sequence[str], None] = 'e6aa9e30d49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # page_embeddings needs pgvector: the image built from database/Dockerfile has it.
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('normalized_key', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('PERSON', 'ORGANIZATION', 'EVENT', 'OTHER', name='entity_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_ne', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('normalized_key', name=op.f('uq_entities_normalized_key'))
    )
    op.create_table('page_embeddings',
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_page_embeddings_chunk_index_non_negative')),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_page_embeddings_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_embeddings')),
    sa.UniqueConstraint('page_id', 'model_name', 'chunk_index', name='uq_page_embeddings_page_model_chunk')
    )
    op.create_index('ix_page_embeddings_embedding_hnsw', 'page_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_page_embeddings_page_id'), 'page_embeddings', ['page_id'], unique=False)
    op.create_table('page_entities',
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('salience', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('mention_count >= 1', name=op.f('ck_page_entities_mention_count_positive')),
    sa.CheckConstraint('salience IS NULL OR (salience >= 0 AND salience <= 1)', name=op.f('ck_page_entities_salience_range')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_page_entities_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_page_entities_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_entities')),
    sa.UniqueConstraint('page_id', 'entity_id', name='uq_page_entities_page_entity')
    )
    op.create_index(op.f('ix_page_entities_entity_id'), 'page_entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_page_entities_page_id'), 'page_entities', ['page_id'], unique=False)
    op.create_table('page_media',
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('stored_file_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'DOCUMENT', name='media_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_page_media_page_id_pages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stored_file_id'], ['stored_files.id'], name=op.f('fk_page_media_stored_file_id_stored_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_media')),
    sa.UniqueConstraint('page_id', 'url', name='uq_page_media_page_url')
    )
    op.create_index(op.f('ix_page_media_page_id'), 'page_media', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_media_stored_file_id'), 'page_media', ['stored_file_id'], unique=False)
    op.create_table('page_sources',
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('crawled_document_id', sa.BigInteger(), nullable=True),
    sa.Column('stored_file_id', sa.BigInteger(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_changed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(crawled_document_id, stored_file_id) = 1', name=op.f('ck_page_sources_one_source')),
    sa.ForeignKeyConstraint(['crawled_document_id'], ['crawled_documents.id'], name=op.f('fk_page_sources_crawled_document_id_crawled_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_page_sources_page_id_pages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stored_file_id'], ['stored_files.id'], name=op.f('fk_page_sources_stored_file_id_stored_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_sources')),
    sa.UniqueConstraint('page_id', 'crawled_document_id', 'stored_file_id', name='uq_page_sources_page_source', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_page_sources_crawled_document_id'), 'page_sources', ['crawled_document_id'], unique=False)
    op.create_index(op.f('ix_page_sources_page_id'), 'page_sources', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_sources_stored_file_id'), 'page_sources', ['stored_file_id'], unique=False)
    op.add_column('pages', sa.Column('language_confidence', sa.Float(), nullable=True))
    op.add_column('pages', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('pages', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('pages', sa.Column('quality_flags', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('pages', sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('pages', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('pages', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_index('ix_pages_category', 'pages', ['category'], unique=False)
    # ### end Alembic commands ###
    # Autogenerate does not detect CHECK constraints.
    op.create_check_constraint(
        op.f('ck_pages_language_confidence_range'),
        'pages',
        'language_confidence IS NULL OR (language_confidence >= 0 AND language_confidence <= 1)',
    )
    op.create_check_constraint(op.f('ck_pages_version_positive'), 'pages', 'version >= 1')
    # Existing pages keep their real history rather than this migration's timestamp.
    op.execute('UPDATE pages SET first_seen_at = created_at, last_seen_at = updated_at')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pages_category', table_name='pages')
    op.drop_column('pages', 'version')
    op.drop_column('pages', 'last_seen_at')
    op.drop_column('pages', 'first_seen_at')
    op.drop_column('pages', 'quality_flags')
    op.drop_column('pages', 'author')
    op.drop_column('pages', 'category')
    op.drop_column('pages', 'language_confidence')
    op.drop_index(op.f('ix_page_sources_stored_file_id'), table_name='page_sources')
    op.drop_index(op.f('ix_page_sources_page_id'), table_name='page_sources')
    op.drop_index(op.f('ix_page_sources_crawled_document_id'), table_name='page_sources')
    op.drop_table('page_sources')
    op.drop_index(op.f('ix_page_media_stored_file_id'), table_name='page_media')
    op.drop_index(op.f('ix_page_media_page_id'), table_name='page_media')
    op.drop_table('page_media')
    op.drop_index(op.f('ix_page_entities_page_id'), table_name='page_entities')
    op.drop_index(op.f('ix_page_entities_entity_id'), table_name='page_entities')
    op.drop_table('page_entities')
    op.drop_index(op.f('ix_page_embeddings_page_id'), table_name='page_embeddings')
    op.drop_index('ix_page_embeddings_embedding_hnsw', table_name='page_embeddings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('page_embeddings')
    op.drop_table('entities')
    # ### end Alembic commands ###
