"""pages from stored files

Revision ID: e6aa9e30d49a
Revises: e529ca38e6ae
Create Date: 2026-09-26 09:16:02.452293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6aa9e30d49a'
down_revision: Union[str, Sequence[str], None] = 'e529ca38e6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('stored_file_id', sa.BigInteger(), nullable=True))
    op.alter_column('pages', 'crawled_document_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_pages_stored_file_id'), 'pages', ['stored_file_id'], unique=False)
    op.create_foreign_key(op.f('fk_pages_stored_file_id_stored_files'), 'pages', 'stored_files', ['stored_file_id'], ['id'], ondelete='RESTRICT')
    op.add_column('stored_files', sa.Column('processing_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # Autogenerate does not detect CHECK constraints.
    op.create_check_constraint(
        op.f('ck_pages_one_source'),
        'pages',
        'num_nonnulls(crawled_document_id, stored_file_id) = 1',
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Pages built from a stored file have no Bronze page to fall back to.
    op.execute('DELETE FROM pages WHERE crawled_document_id IS NULL')
    op.drop_constraint(op.f('ck_pages_one_source'), 'pages', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stored_files', 'processing_error')
    op.drop_constraint(op.f('fk_pages_stored_file_id_stored_files'), 'pages', type_='foreignkey')
    op.drop_index(op.f('ix_pages_stored_file_id'), table_name='pages')
    op.alter_column('pages', 'crawled_document_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('pages', 'stored_file_id')
    # ### end Alembic commands ###
