"""gold: geo content stats, page scores, search logs

Revision ID: d4e5f6a7b8c9
Revises: c3d4e5f6a7b8
Create Date: 2026-09-29 21:07:03.936200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# search_documents gains the ranking signals. CREATE OR REPLACE may only append
# columns, so the old ones keep their order; downgrade recreates the old view.
_SEARCH_DOCUMENTS_BODY = r"""
SELECT p.id AS page_id,
       p.canonical_url AS url,
       p.domain_id,
       coalesce(
           dm.domain,
           -- host of the URL, without "www." or a port
           lower(regexp_replace(
               substring(p.canonical_url from '^[a-zA-Z][a-zA-Z0-9+.-]*://([^/?#]+)'),
               '^www\.|:[0-9]+$', '', 'g'
           ))
       ) AS domain,
       p.title,
       p.description,
       p.language,
       p.content_type,
       p.category,
       p.author,
       p.published_at,
       p.keywords,
       p.word_count,
       g.province_code,
       g.district_code,
       g.local_body_code,
       g.ward_number,
       sf.content_type AS file_mime_type,
       sf.size_bytes AS file_size_bytes,
       lower(substring(sf.document_url from '\.([A-Za-z0-9]{1,8})(?:[?#].*)?$')) AS file_extension,
       p.processing_status AS index_status,
       p.version,
       p.content_hash,
       p.updated_at{extra_columns}
FROM pages p
LEFT JOIN domains dm ON dm.id = p.domain_id
LEFT JOIN stored_files sf ON sf.id = p.stored_file_id
LEFT JOIN LATERAL (
    SELECT c.province_code, c.district_code, c.local_body_code, c.ward_number
    FROM page_geo_codes c
    WHERE c.page_id = p.id
    ORDER BY c.confidence DESC,
             c.local_body_code IS NULL,
             c.district_code IS NULL,
             c.ward_number IS NULL,
             c.tag_id
    LIMIT 1
) g ON true{extra_joins}
WHERE p.duplicate_of_id IS NULL
"""

_SCORE_COLUMNS = """,
       ps.pagerank,
       ps.inbound_links,
       ps.freshness_score,
       ps.quality_score,
       ps.static_rank,
       ds.authority_score AS domain_authority"""

_SCORE_JOINS = """
LEFT JOIN page_scores ps ON ps.page_id = p.id
LEFT JOIN domain_stats ds ON ds.domain_id = p.domain_id"""



def _view_body(columns: str, joins: str) -> str:
    # str.replace, not str.format: the regexes contain {1,8}.
    return _SEARCH_DOCUMENTS_BODY.replace('{extra_columns}', columns).replace('{extra_joins}', joins)


# revision identifiers, used by Alembic.
revision: str = 'd4e5f6a7b8c9'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_queries',
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=False),
    sa.Column('query_language', sa.String(length=16), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_number', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('result_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_search_queries_latency_non_negative')),
    sa.CheckConstraint('page_number >= 1', name=op.f('ck_search_queries_page_number_positive')),
    sa.CheckConstraint('result_count >= 0', name=op.f('ck_search_queries_result_count_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_queries'))
    )
    op.create_index('ix_search_queries_normalized_query', 'search_queries', ['normalized_query'], unique=False)
    op.create_index('ix_search_queries_searched_at', 'search_queries', ['searched_at'], unique=False, postgresql_using='brin')
    op.create_index('ix_search_queries_session_id', 'search_queries', ['session_id'], unique=False)
    op.create_table('geo_content_stats',
    sa.Column('province_code', sa.String(length=4), nullable=True),
    sa.Column('district_code', sa.String(length=4), nullable=True),
    sa.Column('local_body_code', sa.String(length=16), nullable=True),
    sa.Column('page_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('document_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('domain_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latest_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('by_content_type', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('by_language', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('by_category', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(province_code, district_code, local_body_code) = 1', name=op.f('ck_geo_content_stats_exactly_one_region')),
    sa.CheckConstraint('page_count >= 0 AND document_count >= 0 AND domain_count >= 0', name=op.f('ck_geo_content_stats_counts_non_negative')),
    sa.ForeignKeyConstraint(['district_code'], ['districts.code'], name=op.f('fk_geo_content_stats_district_code_districts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['local_body_code'], ['local_bodies.code'], name=op.f('fk_geo_content_stats_local_body_code_local_bodies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_code'], ['provinces.code'], name=op.f('fk_geo_content_stats_province_code_provinces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geo_content_stats')),
    sa.UniqueConstraint('province_code', 'district_code', 'local_body_code', name='uq_geo_content_stats_region', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_geo_content_stats_district_code'), 'geo_content_stats', ['district_code'], unique=False)
    op.create_index(op.f('ix_geo_content_stats_local_body_code'), 'geo_content_stats', ['local_body_code'], unique=False)
    op.create_index(op.f('ix_geo_content_stats_province_code'), 'geo_content_stats', ['province_code'], unique=False)
    op.create_table('page_scores',
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('pagerank', sa.Float(), nullable=False),
    sa.Column('inbound_links', sa.Integer(), server_default='0', nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('static_rank', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('freshness_score BETWEEN 0 AND 1 AND quality_score BETWEEN 0 AND 1 AND static_rank BETWEEN 0 AND 1', name=op.f('ck_page_scores_scores_in_range')),
    sa.CheckConstraint('inbound_links >= 0', name=op.f('ck_page_scores_inbound_links_non_negative')),
    sa.CheckConstraint('pagerank >= 0', name=op.f('ck_page_scores_pagerank_non_negative')),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_page_scores_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_scores')),
    sa.UniqueConstraint('page_id', name=op.f('uq_page_scores_page_id'))
    )
    op.create_index('ix_page_scores_static_rank', 'page_scores', ['static_rank'], unique=False)
    op.create_table('relevance_judgments',
    sa.Column('normalized_query', sa.Text(), nullable=False),
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.Enum('HUMAN', 'CLICK_MODEL', name='judgment_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('judged_by', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade BETWEEN 0 AND 3', name=op.f('ck_relevance_judgments_grade_range')),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_relevance_judgments_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relevance_judgments')),
    sa.UniqueConstraint('normalized_query', 'page_id', 'judged_by', name='uq_relevance_judgments_label')
    )
    op.create_index(op.f('ix_relevance_judgments_normalized_query'), 'relevance_judgments', ['normalized_query'], unique=False)
    op.create_index(op.f('ix_relevance_judgments_page_id'), 'relevance_judgments', ['page_id'], unique=False)
    op.create_table('search_clicks',
    sa.Column('search_query_id', sa.BigInteger(), nullable=False),
    sa.Column('page_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dwell_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dwell_ms IS NULL OR dwell_ms >= 0', name=op.f('ck_search_clicks_dwell_non_negative')),
    sa.CheckConstraint('rank_position >= 1', name=op.f('ck_search_clicks_rank_position_positive')),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_search_clicks_page_id_pages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], name=op.f('fk_search_clicks_search_query_id_search_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_clicks'))
    )
    op.create_index(op.f('ix_search_clicks_page_id'), 'search_clicks', ['page_id'], unique=False)
    op.create_index(op.f('ix_search_clicks_search_query_id'), 'search_clicks', ['search_query_id'], unique=False)
    op.add_column('domain_stats', sa.Column('inbound_link_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('domain_stats', sa.Column('authority_score', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###
    # Autogenerate does not see CHECK changes.
    op.drop_constraint(op.f('ck_domain_stats_counts_non_negative'), 'domain_stats', type_='check')
    op.create_check_constraint(
        op.f('ck_domain_stats_counts_non_negative'),
        'domain_stats',
        'discovered_links >= 0 AND scraped_pages >= 0 AND failed_pages >= 0'
        ' AND page_count >= 0 AND quarantined_count >= 0 AND inbound_link_count >= 0',
    )
    op.create_check_constraint(
        op.f('ck_domain_stats_authority_score_range'),
        'domain_stats',
        'authority_score >= 0 AND authority_score <= 1',
    )
    op.execute(
        'CREATE OR REPLACE VIEW search_documents AS'
        + _view_body(_SCORE_COLUMNS, _SCORE_JOINS)
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute('DROP VIEW search_documents')
    op.execute(
        'CREATE VIEW search_documents AS'
        + _view_body('', '')
    )
    op.drop_constraint(op.f('ck_domain_stats_authority_score_range'), 'domain_stats', type_='check')
    op.drop_constraint(op.f('ck_domain_stats_counts_non_negative'), 'domain_stats', type_='check')
    op.create_check_constraint(
        op.f('ck_domain_stats_counts_non_negative'),
        'domain_stats',
        'discovered_links >= 0 AND scraped_pages >= 0 AND failed_pages >= 0'
        ' AND page_count >= 0 AND quarantined_count >= 0',
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain_stats', 'authority_score')
    op.drop_column('domain_stats', 'inbound_link_count')
    op.drop_index(op.f('ix_search_clicks_search_query_id'), table_name='search_clicks')
    op.drop_index(op.f('ix_search_clicks_page_id'), table_name='search_clicks')
    op.drop_table('search_clicks')
    op.drop_index(op.f('ix_relevance_judgments_page_id'), table_name='relevance_judgments')
    op.drop_index(op.f('ix_relevance_judgments_normalized_query'), table_name='relevance_judgments')
    op.drop_table('relevance_judgments')
    op.drop_index('ix_page_scores_static_rank', table_name='page_scores')
    op.drop_table('page_scores')
    op.drop_index(op.f('ix_geo_content_stats_province_code'), table_name='geo_content_stats')
    op.drop_index(op.f('ix_geo_content_stats_local_body_code'), table_name='geo_content_stats')
    op.drop_index(op.f('ix_geo_content_stats_district_code'), table_name='geo_content_stats')
    op.drop_table('geo_content_stats')
    op.drop_index('ix_search_queries_session_id', table_name='search_queries')
    op.drop_index('ix_search_queries_searched_at', table_name='search_queries', postgresql_using='brin')
    op.drop_index('ix_search_queries_normalized_query', table_name='search_queries')
    op.drop_table('search_queries')
    # ### end Alembic commands ###
