"""bronze ingest state for the S3 loader

Revision ID: a7b8c9d0e1f2
Revises: f6a7b8c9d0e1
Create Date: 2026-09-30 09:22:27.464458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgs_db import grants


# revision identifiers, used by Alembic.
revision: str = 'a7b8c9d0e1f2'
down_revision: Union[str, Sequence[str], None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bronze_ingest_state',
    sa.Column('crawl_run_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('objects_loaded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('objects_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('finished', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('objects_loaded >= 0 AND objects_failed >= 0', name=op.f('ck_bronze_ingest_state_counts_non_negative')),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], name=op.f('fk_bronze_ingest_state_crawl_run_id_crawl_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bronze_ingest_state')),
    sa.UniqueConstraint('crawl_run_id', name=op.f('uq_bronze_ingest_state_crawl_run_id'))
    )
    # ### end Alembic commands ###
    op.execute(
        'CREATE TRIGGER trg_bronze_ingest_state_updated_at BEFORE UPDATE ON bronze_ingest_state '
        'FOR EACH ROW EXECUTE FUNCTION pgs_set_updated_at()'
    )
    grants.apply(op.execute)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bronze_ingest_state')
    # ### end Alembic commands ###
