"""region links, search views

Revision ID: b7c1d2e3f4a5
Revises: 8994296d4b0e
Create Date: 2026-09-29 20:00:41.567979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Frozen copies of the view SQL; pgs_db.models.views describes the columns.
_PAGE_GEO_CODES_SQL = """
CREATE VIEW page_geo_codes AS
SELECT t.id AS tag_id,
       t.page_id,
       coalesce(t.province_code, d.province_code) AS province_code,
       coalesce(t.district_code, lb.district_code) AS district_code,
       t.local_body_code,
       t.ward_number,
       t.method,
       t.confidence
FROM page_geo_tags t
LEFT JOIN local_bodies lb ON lb.code = t.local_body_code
LEFT JOIN districts d ON d.code = coalesce(t.district_code, lb.district_code)
"""

_SEARCH_DOCUMENTS_SQL = r"""
CREATE VIEW search_documents AS
SELECT p.id AS page_id,
       p.canonical_url AS url,
       p.domain_id,
       coalesce(
           dm.domain,
           -- host of the URL, without "www." or a port
           lower(regexp_replace(
               substring(p.canonical_url from '^[a-zA-Z][a-zA-Z0-9+.-]*://([^/?#]+)'),
               '^www\.|:[0-9]+$', '', 'g'
           ))
       ) AS domain,
       p.title,
       p.description,
       p.language,
       p.content_type,
       p.category,
       p.author,
       p.published_at,
       p.keywords,
       p.word_count,
       g.province_code,
       g.district_code,
       g.local_body_code,
       g.ward_number,
       sf.content_type AS file_mime_type,
       sf.size_bytes AS file_size_bytes,
       lower(substring(sf.document_url from '\.([A-Za-z0-9]{1,8})(?:[?#].*)?$')) AS file_extension,
       p.processing_status AS index_status,
       p.version,
       p.content_hash,
       p.updated_at
FROM pages p
LEFT JOIN domains dm ON dm.id = p.domain_id
LEFT JOIN stored_files sf ON sf.id = p.stored_file_id
LEFT JOIN LATERAL (
    SELECT c.province_code, c.district_code, c.local_body_code, c.ward_number
    FROM page_geo_codes c
    WHERE c.page_id = p.id
    ORDER BY c.confidence DESC,
             c.local_body_code IS NULL,
             c.district_code IS NULL,
             c.ward_number IS NULL,
             c.tag_id
    LIMIT 1
) g ON true
WHERE p.duplicate_of_id IS NULL
"""


# revision identifiers, used by Alembic.
revision: str = 'b7c1d2e3f4a5'
down_revision: Union[str, Sequence[str], None] = '8994296d4b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_links',
    sa.Column('province_code', sa.String(length=4), nullable=True),
    sa.Column('district_code', sa.String(length=4), nullable=True),
    sa.Column('local_body_code', sa.String(length=16), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('title_ne', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("url ~* '^https?://'", name=op.f('ck_region_links_url_http')),
    sa.CheckConstraint('num_nonnulls(province_code, district_code, local_body_code) = 1', name=op.f('ck_region_links_exactly_one_region')),
    sa.ForeignKeyConstraint(['district_code'], ['districts.code'], name=op.f('fk_region_links_district_code_districts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['local_body_code'], ['local_bodies.code'], name=op.f('fk_region_links_local_body_code_local_bodies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_code'], ['provinces.code'], name=op.f('fk_region_links_province_code_provinces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region_links')),
    sa.UniqueConstraint('province_code', 'district_code', 'local_body_code', 'url', name='uq_region_links_region_url', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_region_links_district_code'), 'region_links', ['district_code'], unique=False)
    op.create_index(op.f('ix_region_links_local_body_code'), 'region_links', ['local_body_code'], unique=False)
    op.create_index(op.f('ix_region_links_province_code'), 'region_links', ['province_code'], unique=False)
    # ### end Alembic commands ###
    op.execute(_PAGE_GEO_CODES_SQL)
    op.execute(_SEARCH_DOCUMENTS_SQL)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW search_documents")
    op.execute("DROP VIEW page_geo_codes")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_region_links_province_code'), table_name='region_links')
    op.drop_index(op.f('ix_region_links_local_body_code'), table_name='region_links')
    op.drop_index(op.f('ix_region_links_district_code'), table_name='region_links')
    op.drop_table('region_links')
    # ### end Alembic commands ###
