"""admin users, error logs, domain stats

Revision ID: 8994296d4b0e
Revises: 8aa170eaaf03
Create Date: 2026-09-29 19:42:21.949596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8994296d4b0e'
down_revision: Union[str, Sequence[str], None] = '8aa170eaaf03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'SYSTEM_OPERATOR', 'AUDITOR', name='admin_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_admin_users_email_lowercase')),
    sa.CheckConstraint('length(password_hash) > 0', name=op.f('ck_admin_users_password_hash_not_empty')),
    sa.CheckConstraint("position('@' in username) = 0", name=op.f('ck_admin_users_username_no_at')),
    sa.CheckConstraint('username = lower(username)', name=op.f('ck_admin_users_username_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_admin_users_username'))
    )
    op.create_table('domain_stats',
    sa.Column('domain_id', sa.BigInteger(), nullable=False),
    sa.Column('discovered_links', sa.Integer(), server_default='0', nullable=False),
    sa.Column('scraped_pages', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_pages', sa.Integer(), server_default='0', nullable=False),
    sa.Column('page_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quarantined_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discovered_links >= 0 AND scraped_pages >= 0 AND failed_pages >= 0 AND page_count >= 0 AND quarantined_count >= 0', name=op.f('ck_domain_stats_counts_non_negative')),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_domain_stats_domain_id_domains'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_stats')),
    sa.UniqueConstraint('domain_id', name=op.f('uq_domain_stats_domain_id'))
    )
    op.create_table('error_logs',
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('service', sa.Enum('SCRAPER', 'ETL', 'SECURITY', 'SEARCH', 'API', name='service_name', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('instance', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.Enum('WARN', 'ERROR', 'FATAL', name='log_severity', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('domain_id', sa.BigInteger(), nullable=True),
    sa.Column('crawl_run_id', sa.BigInteger(), nullable=True),
    sa.Column('crawled_document_id', sa.BigInteger(), nullable=True),
    sa.Column('page_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], name=op.f('fk_error_logs_crawl_run_id_crawl_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crawled_document_id'], ['crawled_documents.id'], name=op.f('fk_error_logs_crawled_document_id_crawled_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_error_logs_domain_id_domains'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_error_logs_page_id_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_logs'))
    )
    op.create_index(op.f('ix_error_logs_domain_id'), 'error_logs', ['domain_id'], unique=False)
    op.create_index(op.f('ix_error_logs_occurred_at'), 'error_logs', ['occurred_at'], unique=False)
    op.create_index('ix_error_logs_service_severity_occurred_at', 'error_logs', ['service', 'severity', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_error_logs_service_severity_occurred_at', table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_occurred_at'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_domain_id'), table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_table('domain_stats')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
