"""create bronze and reference tables

Revision ID: 95e7b8aa6ec5
Revises:
Create Date: 2026-09-22 02:39:00.377758

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "95e7b8aa6ec5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_runs",
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="crawl_run_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("temporal_workflow_id", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_count", sa.Integer(), nullable=False),
        sa.Column("succeeded_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("unique_url_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_runs")),
    )
    op.create_table(
        "provinces",
        sa.Column("code", sa.String(length=4), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=False),
        sa.Column("name_ne", sa.String(length=100), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provinces")),
        sa.UniqueConstraint("code", name=op.f("uq_provinces_code")),
    )
    op.create_table(
        "districts",
        sa.Column("code", sa.String(length=4), nullable=False),
        sa.Column("province_code", sa.String(length=4), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=False),
        sa.Column("name_ne", sa.String(length=100), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["province_code"], ["provinces.code"], name=op.f("fk_districts_province_code_provinces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_districts")),
        sa.UniqueConstraint("code", name=op.f("uq_districts_code")),
    )
    op.create_index(
        op.f("ix_districts_province_code"), "districts", ["province_code"], unique=False
    )
    op.create_table(
        "local_bodies",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("district_code", sa.String(length=4), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "METROPOLITAN_CITY",
                "SUB_METROPOLITAN_CITY",
                "MUNICIPALITY",
                "RURAL_MUNICIPALITY",
                name="local_body_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("name_en", sa.String(length=150), nullable=False),
        sa.Column("name_ne", sa.String(length=150), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["district_code"],
            ["districts.code"],
            name=op.f("fk_local_bodies_district_code_districts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_local_bodies")),
        sa.UniqueConstraint("code", name=op.f("uq_local_bodies_code")),
    )
    op.create_index(
        op.f("ix_local_bodies_district_code"), "local_bodies", ["district_code"], unique=False
    )
    op.create_table(
        "domains",
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("website_name", sa.String(length=255), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "GOVERNMENT",
                "NEWS",
                "EDUCATION",
                "FINANCE",
                "NGO",
                "COMMERCIAL",
                "OTHER",
                name="domain_category",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CRAWLING",
                "PAUSED",
                "COMPLETED",
                "FAILED",
                name="domain_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW",
                "NORMAL",
                "HIGH",
                name="domain_priority",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("rate_limit_per_sec", sa.Integer(), nullable=False),
        sa.Column("local_body_id", sa.BigInteger(), nullable=True),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rate_limit_per_sec > 0", name=op.f("ck_domains_rate_limit_positive")),
        sa.ForeignKeyConstraint(
            ["local_body_id"],
            ["local_bodies.id"],
            name=op.f("fk_domains_local_body_id_local_bodies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domains")),
        sa.UniqueConstraint("domain", name=op.f("uq_domains_domain")),
    )
    op.create_index(op.f("ix_domains_local_body_id"), "domains", ["local_body_id"], unique=False)
    op.create_index(op.f("ix_domains_status"), "domains", ["status"], unique=False)
    op.create_table(
        "crawled_documents",
        sa.Column("crawl_run_id", sa.BigInteger(), nullable=True),
        sa.Column("domain_id", sa.BigInteger(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("normalized_url", sa.Text(), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.Column("meta_keywords", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("open_graph", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("headings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("json_ld", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("emails", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("phones", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("social_links", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("links", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("anchor_texts", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("internal_links", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("external_links", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("image_links", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("video_links", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("geo_lat", sa.Float(), nullable=True),
        sa.Column("geo_lng", sa.Float(), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("sim_hash", sa.BigInteger(), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetch_duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("minio_path", sa.Text(), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum(
                "UNPROCESSED",
                "PROCESSING",
                "PROCESSED",
                "FAILED",
                name="processing_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="UNPROCESSED",
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["crawl_run_id"],
            ["crawl_runs.id"],
            name=op.f("fk_crawled_documents_crawl_run_id_crawl_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"], ["domains.id"], name=op.f("fk_crawled_documents_domain_id_domains")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawled_documents")),
        sa.UniqueConstraint(
            "normalized_url",
            "content_hash",
            name=op.f("uq_crawled_documents_normalized_url_content_hash"),
        ),
    )
    op.create_index(
        op.f("ix_crawled_documents_crawl_run_id"),
        "crawled_documents",
        ["crawl_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawled_documents_domain_id"), "crawled_documents", ["domain_id"], unique=False
    )
    op.create_index(
        op.f("ix_crawled_documents_fetched_at"), "crawled_documents", ["fetched_at"], unique=False
    )
    op.create_index(op.f("ix_crawled_documents_host"), "crawled_documents", ["host"], unique=False)
    op.create_index(
        op.f("ix_crawled_documents_processing_status"),
        "crawled_documents",
        ["processing_status"],
        unique=False,
    )
    op.create_table(
        "stored_files",
        sa.Column("crawled_document_id", sa.BigInteger(), nullable=True),
        sa.Column("source_page_url", sa.Text(), nullable=False),
        sa.Column("document_url", sa.Text(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("stored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "processing_status",
            sa.Enum(
                "UNPROCESSED",
                "PROCESSING",
                "PROCESSED",
                "FAILED",
                name="processing_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="UNPROCESSED",
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["crawled_document_id"],
            ["crawled_documents.id"],
            name=op.f("fk_stored_files_crawled_document_id_crawled_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_files")),
        sa.UniqueConstraint(
            "document_url", "sha256", name=op.f("uq_stored_files_document_url_sha256")
        ),
    )
    op.create_index(
        op.f("ix_stored_files_crawled_document_id"),
        "stored_files",
        ["crawled_document_id"],
        unique=False,
    )
    op.create_index(op.f("ix_stored_files_sha256"), "stored_files", ["sha256"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stored_files_sha256"), table_name="stored_files")
    op.drop_index(op.f("ix_stored_files_crawled_document_id"), table_name="stored_files")
    op.drop_table("stored_files")
    op.drop_index(op.f("ix_crawled_documents_processing_status"), table_name="crawled_documents")
    op.drop_index(op.f("ix_crawled_documents_host"), table_name="crawled_documents")
    op.drop_index(op.f("ix_crawled_documents_fetched_at"), table_name="crawled_documents")
    op.drop_index(op.f("ix_crawled_documents_domain_id"), table_name="crawled_documents")
    op.drop_index(op.f("ix_crawled_documents_crawl_run_id"), table_name="crawled_documents")
    op.drop_table("crawled_documents")
    op.drop_index(op.f("ix_domains_status"), table_name="domains")
    op.drop_index(op.f("ix_domains_local_body_id"), table_name="domains")
    op.drop_table("domains")
    op.drop_index(op.f("ix_local_bodies_district_code"), table_name="local_bodies")
    op.drop_table("local_bodies")
    op.drop_index(op.f("ix_districts_province_code"), table_name="districts")
    op.drop_table("districts")
    op.drop_table("provinces")
    op.drop_table("crawl_runs")
    # ### end Alembic commands ###
